Updated to test

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -123,6 +123,7 @@ jobs:
         # Build image with packer
         - name: Packer build
           run: |
+            packer build build-mi.pkr.hcl
             image_id=$(gcloud compute images list --filter="family=csye6225-app-image" --format="value(NAME)" --sort-by=~creationTimestamp --limit=1)
             echo "IMAGE_ID=$image_id" >> $GITHUB_ENV
             echo "Image ID: $image_id"
@@ -145,7 +146,26 @@ jobs:
             --network=vpc-def \
             --subnet=vpc-def-webapp \
             --scopes='https://www.googleapis.com/auth/cloud-platform' \
+            --metadata=startup-script='#!/bin/bash
+
+                                        if [ ! -f "/opt/db.properties" ] 
+                                        then
+                                        sudo touch /opt/db.properties
                                         
+                                        sudo echo "spring.datasource.url=jdbc:mysql://${google_sql_database_instance.database_instance.first_ip_address}:3306/${google_sql_database.database.name}?createDatabaseIfNotExist=true" >> /opt/db.properties
+                                        sudo echo "spring.datasource.username=${google_sql_user.users.name}" >> /opt/db.properties
+                                        sudo echo "spring.datasource.password=${google_sql_user.users.password}" >> /opt/db.properties
+                                        sudo echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> /opt/db.properties
+                                        sudo echo "spring.jpa.hibernate.ddl-auto=update" >> /opt/db.properties
+                                        sudo echo "spring.jpa.show-sql=true" >> /opt/db.properties
+                                        sudo echo "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect" >> /opt/db.properties
+                                        
+                                        sudo chown -R csye6225:csye6225 /opt/db.properties
+                                        else
+                                        sudo echo "db.properties already exists" >> /var/log/csye6225/app.log
+                                        fi
+                                        sudo touch /opt/pubsub-service-account-key.json'
+                                                                    
 
         - name: Refresh instances
           run: |
@@ -157,41 +177,24 @@ jobs:
             --max-unavailable=1 \
             --quiet
 
-        - name: Wait for MIG refresh to complete
-          id: wait_for_refresh
+        - name: Check Status
           run: |
-              # Poll the status of the MIG until it's completed refreshing
-              while true; do
-                STATUS=$(gcloud compute instance-groups managed describe ${{ vars.GROUP_MANAGER}} \
-                  --project=${{ vars.PROJECT_ID }} \
-                  --region=${{ vars.REGION}} \
-                  --format="value(status)")
-    
-                STATUS=$(echo $STATUS | jq -r isReached)
-                if [[ $STATUS == "REFRESHING" ]]; then
-                  echo "MIG is still refreshing. Waiting..."
-                  sleep 10
-                else
-                  echo "MIG refresh completed."
+                status=$(gcloud compute instance-groups managed wait-until webapp-igm --region=us-east4 --stable)
+                echo "Status: $status"
+                if [[ $status == "Group is stable" ]]; then
+                  echo "Refreshed successfully"
                   break
+                else
+                  echo "Refresh Failed"
+                  exit 1
                 fi
-              done
-    
-        - name: Check MIG refresh status
-          run: |
-              # Check the final status of the MIG refresh
-              STATUS=$(gcloud compute instance-groups managed describe ${{ vars.GROUP_MANAGER}} \
-                --project=${{ vars.PROJECT_ID }} \
-                --region=${{ vars.REGION }} \
-                --format=json)
-
-              STATUS=$(echo $STATUS | jq -r isReached)
-    
-              if [[ $STATUS != "True" ]]; then
-                echo "MIG refresh failed."
+                if [ "$status" == "UPDATING" ]; then
+                  echo "IGM is still updating..."
+                  exit 1
+                fi
+                if [ "$status" == "READY" ]; then
+                  echo "IGM is ready!"
+                  exit 0
+                fi
                 exit 1
-              else
-                echo "MIG refresh successful."
-              fi
-
             
